### ISSUE TITLE
lots of problems

### ISSUE THREAD

**Issue by NorHei** [cwsoft/wbce-addon-file-editor#1]
Trying to install AFE on mostl recent WBCE  i get 

Notice: Use of undefined constant WBCE_VERSION - assumed 'WBCE_VERSION' in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 167
Add-On Voraussetzungen nicht erfüllt

Installation fehlgeschlagen. Ihr System erfüllt nicht alle Voraussetzungen die für diese Erweiterung benötigt werden. Um diese Erweiterung nutzen zu können, müssen nachfolgende Updates durchgeführt werden.

Warning: Illegal string offset 'status' in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 321

Warning: Invalid argument supplied for foreach() in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 322

Warning: Illegal string offset 'status' in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 321

Warning: Invalid argument supplied for foreach() in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 322

Warning: Illegal string offset 'status' in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 321

Warning: Invalid argument supplied for foreach() in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 322

Warning: Invalid argument supplied for foreach() in /var/www/web913/html/eso/wbce2/framework/addon.precheck.inc.php on line 322
Voraussetzung:	Erforderlich:	Aktuell:
PHP-Version:	>= 5.3.6	5.6.6

**Comment by cwsoft** [comment]
Is this error still present in the latest release of WBCE and AFE.

**Comment by NorHei** [comment]
then please have a look , i never used AFE

**Comment by cwsoft** [comment]
I will test once Git and a local XAMPP server is available on iPhone, my only connection to the WWW for the past and the next weeks to come.

**Comment by NorHei** [comment]
Oh, you are still away...

**Comment by NorHei** [comment]
Sorry, i misread your post .

I read that the error is still present . 

But no it isn't  just tested it whith latest AFE and latest Master WBCE 

Sorry again!
