### ISSUE TITLE
PHP 7.0.5: Zip download doesn't work 

### ISSUE THREAD

**Issue by instantflorian** [cwsoft/wbce-addon-file-editor#3]
When clicking on zip download icon (mo matter if module or template), a new browser tab open and just a plain error message  occurs:
Parse error: syntax error, unexpected 'new' (T_NEW) in /.../modules/cwsoft-addon-file-editor/thirdparty/PEAR/Download.php on line 252
(The zipfile is generated nevertheless, but not offered for download)

**Comment by cwsoft** [comment]
Confirmed, thanks for reporting. As a quickfix one can remove the assignement by reference from /thirdparty/PEAR/Download.php code lines 253 and 768, wich is no longer supported in PHP7.

PHP 4/5: 
`$d = &new HTTP_Download()`

PHP 7:
`$d = new HTTP_Download()`

Better solution may be to remove the dependency from PEAR or to switch to HTTP_Download2 which supports PHP7.
